POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_TRANSIENT_PROMPT=always
POWERLEVEL9K_MODE='nerdfont-fontconfig'

typeset -g POWERLEVEL9K_CONTEXT_{DEFAULT,SUDO}_{CONTENT,VISUAL_IDENTIFIER}_EXPANSION=
POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator context dir virtualenv anaconda nvm vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vi_mode time)
POWERLEVEL9K_VI_MODE_BACKGROUND='152'
POWERLEVEL9K_VI_MODE_FOREGROUND='black'

