vim.cmd('source ~/.config/nvim/plugins.vim')
vim.cmd('source ~/.config/nvim/cmp.vim')
require('definitions')
vim.cmd('source ~/.config/nvim/settings.vim')
vim.cmd('source ~/.config/nvim/mappings.vim')
