prSections:
  - title: My Pull Requests
    filters: is:open author:@me
  - title: Needs My Review
    filters: is:open review-requested:@me
  - title: Involved
    filters: is:open involves:@me -author:@me
issuesSections: []
defaults:
  preview:
    open: true
    width: 50
  prsLimit: 10
  issuesLimit: 1
  view: prs
  layout:
    prs:
      updatedAt:
        width: 7
      repo:
        width: 25
      author:
        width: 15
      assignees:
        width: 20
        hidden: true
      base:
        width: 15
        hidden: true
      lines:
        width: 16
  refetchIntervalMinutes: 10
keybindings:
  issues: []
  prs:
    - key: e
      command: >
        tmux new-window -c {{.RepoPath}} 'nvim -c ":Octo pr edit {{.PrNumber}}"'
    - key: v
      command: >
        tmux new-window -c {{.RepoPath}} 'nvim -c ":Octo pr edit {{.PrNumber}}" -c ":sleep 2" -c ":Octo review start"'
    - key: M
      command: >
        gh pr merge --repo {{.RepoName}} {{.PrNumber}} --delete-branch --squash
    - key: t
      command: >
        gh run watch --repo {{.RepoName}}
repoPaths:
  :owner/:repo: ~/workspace/:repo
theme:
  ui:
    table:
      showSeparator: true
  colors:
    text:
      primary: "#cdd6f4"
      secondary: "#89b4fa"
      inverted: "#11111b"
      faint: "#bac2de"
      warning: "#f38ba8"
      success: "#a6e3a1"
      error: "#d14545"
    background:
      selected: "#313244"
    border:
      primary: "#89b4fa"
      secondary: "#45475a"
      faint: "#313244"
pager:
  diff: less
