import = ["/home/alau/.config/alacritty/themes/themes/gruvbox_dark.toml"]

[colors.normal]
green = "#a7dc91"

[colors.primary]
background = "#000000"

[font]
size = 14

[font.normal]
family = "InconsolataGo Nerd Font"
style = "Medium"

[window]
decorations = "none"
