POWERLEVEL9K_PROMPT_ON_NEWLINE=true
POWERLEVEL9K_PROMPT_ADD_NEWLINE=true
POWERLEVEL9K_MODE='nerdfont-fontconfig'

POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(root_indicator dir pyenv nvm vcs)
POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(status vi_mode time)
POWERLEVEL9K_VI_MODE_BACKGROUND='152'
POWERLEVEL9K_VI_MODE_FOREGROUND='black'

